version:  '3'
services: 
  # Backedn API 1
  smart-brain-api_1:
    container_name: backend-api
    build: ./
    environment:
      POSTGRGES_URI: postgres://hieple:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/usr/src/app
    # Backedn API 2
  smart-brain-api_2:
    container_name: backend-api
    build: ./
    environment:
    POSTGRGES_URI: postgres://hieple:secret@postgres:5432/smart-brain-docker
    REDIS_URI: redis://redis:6379
    ports: 
      - "3001:3000"
    volumes: 
      - ./:/usr/src/app
    
    
  # Postgres
  postgres:
    container_name: postgres_db
    environment: 
      POSTGRES_USER: hieple
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports: 
      - "5432:5432"
  
  # Redis
  redis:
    container_name: redis_db
    image: redis
    ports: 
      - "6379:6379"
  #Load_balance
  nginx:
    image: nginx
    ports: 
      - 80:80
    


      